# Generated by Django 3.1.4 on 2021-01-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20210116_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='wine_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='wines.region'),
        ),
    ]
