# Generated by Django 3.1.4 on 2021-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20210116_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wine_type',
            field=models.CharField(choices=[('WHITE', 'White'), ('RED', 'Red'), ('ROSE', 'Rose')], default='WHITE', max_length=100),
        ),
    ]
