# Generated by Django 3.1.4 on 2021-01-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_auto_20210116_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Cheeses',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='wines.cheese'),
        ),
    ]
