# Generated by Django 3.1.4 on 2021-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_remove_region_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
